# 2 Introduction to MATLAB

In [4]:
%load_ext pymatbridge

C:\Anaconda3\lib\site-packages\IPython\nbformat.py:13: ShimWarning: The `IPython.nbformat` package has been deprecated. You should import from nbformat instead.
  "You should import from nbformat instead.", ShimWarning)


Starting MATLAB on ZMQ socket tcp://127.0.0.1:15772
Send 'exit' command to kill the server
...............................................MATLAB started and connected!


## 2.1 MATLAB in Earth Sciences

## 2.2 Getting Started

## 2.3 The Syntax

In [5]:
%%matlab
clear
close all
clc

In [6]:
%%matlab
A = [2 4 3 7; 9 3 -1 2; 1 9 3 7; 6 6 3 -2]


A =

     2     4     3     7
     9     3    -1     2
     1     9     3     7
     6     6     3    -2



In [9]:
%%matlab
A = [2 4 3 7; 9 3 -1 2; 1 9 3 7; 6 6 3 -2];

In [10]:
%%matlab
sum(A)


ans =

    18    22     8    14



In [12]:
%%matlab
b = sum(sum(A));
b


b =

    62



In [13]:
%%matlab
whos

  Name      Size            Bytes  Class     Attributes

  A         4x4               128  double              
  ans       1x4                32  double              
  b         1x1                 8  double              



In [14]:
%%matlab
clear ans

In [15]:
%%matlab
A(3,2)


ans =

     9



In [16]:
%%matlab
A(3,2) = 30


A =

     2     4     3     7
     9     3    -1     2
     1    30     3     7
     6     6     3    -2



In [17]:
%%matlab
A(3,1:4) = [1 3 3 5]


A =

     2     4     3     7
     9     3    -1     2
     1     3     3     5
     6     6     3    -2



In [18]:
%%matlab
A(3,:) = [1 3 3 5]


A =

     2     4     3     7
     9     3    -1     2
     1     3     3     5
     6     6     3    -2



In [19]:
%%matlab
c = 0 : 10


c =

     0     1     2     3     4     5     6     7     8     9    10



In [20]:
%%matlab
whos

  Name      Size            Bytes  Class     Attributes

  A         4x4               128  double              
  ans       1x1                 8  double              
  b         1x1                 8  double              
  c         1x11               88  double              



In [21]:
%%matlab
c = 1 : 0.5 : 10


c =

  Columns 1 through 13

    1.0000    1.5000    2.0000    2.5000    3.0000    3.5000    4.0000    4.5000    5.0000    5.5000    6.0000    6.5000    7.0000

  Columns 14 through 19

    7.5000    8.0000    8.5000    9.0000    9.5000   10.0000



In [22]:
%%matlab
B = [4 2 6 5; 7 8 5 6; 2 1 -8 -9; 3 1 2 3];

In [23]:
%%matlab
C = A * B'


C =

    69   103   -79    37
    46    94    11    34
    53    76   -64    27
    44    93    12    24



In [24]:
%%matlab
C = A .* B


C =

     8     8    18    35
    63    24    -5    12
     2     3   -24   -45
    18     6     6    -6



## 2.4 Array Manipulation

In [ ]:
%%matlab
clear

%%matlab
A = [2 4 3; 9 3 -1]
B = [1 9 3; 6 6 3]

%%matlab
C = cat(1,A,B)
C = vertcat(A,B)

%%matlab
D = cat(2,A,B)
D = horzcat(A,B)

%%matlab
E = cat(3,A,B)

%%matlab
whos

%%matlab
size(E)

%%matlab
length(E)

%%matlab
F = flipud(A)
F = fliplr(A)

%%matlab
G = circshift(A,1,2)

%%matlab
H = reshape(A,[3 2])

%%matlab
I = sort(C,1,'ascend')

%%matlab
J = sortrows(C,2)

%%matlab
A, B

%%matlab
K = ismember(A,B)

%%matlab
L = A
L(find(L<0)) = NaN
L(L<0) = NaN

%%matlab
M = isnan(L)

%%matlab
N = unique(A)

## 2.5 Data Structures and Classes of Objects

In [ ]:
%% Section 2.5matlab
clear

%%matlab
realmin('double')
realmax('double')

%%matlab
eps(1.0)
eps(5.0)

%%matlab
sin(pi)

%%matlab
clear

%%matlab
rng(0)
A = rand(3,4)

%%matlab
format long

%%matlab
A

%%matlab
B = single(A)

%%matlab
format short
A(1,3) = 4i + 3

%%matlab
clear

%%matlab
rng(0)
I1 = 255 * rand(100,100);
I2 = 255 * rand(100,100);
I3 = 255 * rand(100,100);

%%matlab
I = cat(3,I1,I2,I3);

%%matlab
I = uint8(I);

%%matlab
whos

%%matlab
imshow(I)

%%matlab
sample_1.location = 'Plougasnou';
sample_1.date = date;
sample_1.image = I;
sample_1.geochemistry = rand(10,10);

%%matlab
location = 'Plougasnou';

%%matlab
whos location

%%matlab
sample_1.date

%%matlab
sample_1

%%matlab
whos sample_1

%%matlab
C = {'Plougasnou' date I rand(10,10)}

%%matlab
C

%%matlab
C{2}

## 2.6 Data Storage and Handling

In [ ]:
%%matlab
clear

%%matlab
load geochem.txt

%%matlab
whos

%%matlab
save geochem_new.mat

%%matlab
save geochem_new.mat geochem

%%matlab
save geochem_new.txt geochem -ascii

%%matlab
clear

%%matlab
fid = fopen('geochem.txt');
C = textscan(fid,'%u %f %f','Headerlines',1,'CollectOutput',1);
fclose(fid);

%%matlab
C

%%matlab
data1 = C{1}
data2 = C{2}

%%matlab
data(:,1) = double(C{1})
data(:,2:3) = C{2}

%%matlab
clear

%%matlab
fid = fopen('geophys.txt');
data = textscan(fid,'%u %f %f %f %s %s','Headerlines',1);
fclose(fid);

%%matlab
data_date_serial = datenum(data{5});
data_time_serial = datenum(data{6});

%%matlab
data_date = datevec(data_date_serial)
data_time = datevec(data_time_serial)

%%matlab
clear

%%matlab
data = load('geochem.txt');

%%matlab
data = data';

%%matlab
fid = fopen('geochem_formatted.txt','w');
fprintf(fid,'%u %6.4f %6.4f\n',data);
fclose(fid);

%%matlab
edit geochem_formatted.txt

## 2.7 Control Flow

In [ ]:
%% Section 2.7matlab
clear

%%matlab
rng(0)
A = rand(10,1)
for i = 1 : 10
    B(i,1) = round(10 * A(i));   
end    
B

%%matlab
rng(0)
A = rand(10,3)
for i = 1 : 10
    for j = 1 : 3
        B(i,j) = round(10 * A(i,j));  
    end
end    
B

%%matlab
rng(0)
A = rand(10,3)
for i = 1 : size(A,1)
    for j = 1 : size(A,2)
        B(i,j) = round(10 * A(i,j));  
    end
end    
B

%%matlab
clear

%%matlab
rng(0)
A = rand(3,3); A(2,1) = NaN
BC = rand(2,4); BC(2,2) = NaN
DE = rand(1,2); DE(1,1) = NaN
FG = rand(3,2); FG(2,2) = NaN

%%matlab
variables = who;

%%matlab
for i = 1 : size(variables,1)
    v = eval(variables{i});
    v(isnan(v)==1) = -999;
    assignin('base',variables{i},v);
    eval(variables{i})
end

clear i v variables

%%matlab
clear

%%matlab
A = 1
B = 2
if A < B
    disp('A is less than B')
end

%%matlab
A = 1
B = 2
if A < B
    disp('A is less than B')
else
    disp('A is not less than B')
end

%%matlab
A = 1
B = 2
if A < B
    disp('A is less than B')
elseif A >= B
    disp('A is not less than B')
end

## 2.8 Scripts and Functions

In [ ]:
%% Section 2.8matlab
clear

%%matlab
x = [3 6 2 -3 8];

%%matlab
average

%%matlab
whos

%%matlab
a = average

%%matlab
help average

%%matlab
clear

%%matlab
data = [3 6 2 -3 8];

%%matlab
result = average(data);

%%matlab
whos

## 2.9 Basic Visualization Tools

In [ ]:
%% Section 2.9matlab
clear

%%matlab
x = 0 : pi/10 : 2*pi;
y = sin(x);

%%matlab
plot(x,y)

%%matlab
x = 0 : pi/10 : 2*pi;
y1 = sin(x);
y2 = cos(x);

%%matlab
plot(x,y1,'--',x,y2,'-')

%%matlab
plot(x,y1,'--')
figure
plot(x,y2,'-')

%%matlab
plot(x,y1,'r--')
hold on
bar(x,y2)
hold off

%%matlab
subplot(2,1,1), plot(x,y1,'r--')
subplot(2,1,2), bar(x,y2)

%%matlab
clf

%%matlab
plot(x,y1,'r--')
axis([0 pi -1 1])

%%matlab
plot(x,y1,'r--')
axis square

%%matlab
plot(x,y1,'r--')
axis equal

%%matlab
plot(x,y1,'r--')
title('My first plot')
xlabel('x-axis')
ylabel('y-axis')
grid

## 2.10 Generating Code to Recreate Graphics

In [ ]:
%% Section 2.10matlab
clear

%%matlab
x = 0 : pi/10 : 2*pi;
y1 = sin(x);
plot(x,y1)

%%matlab
mygraph(x,y1)

## 2.11 Publishing M-Files

## 2.12 Creating Graphical User Interfaces

In [ ]:
%% Section 2.12matlab
guide

%%matlab
gaussiantool

%%matlab
edit gaussiantool
guide gaussiantool

## Recommended Reading

* Araghinejad S (2014) Data-Driven Modeling: Using MATLAB® in Water Resources and Environmental Engineering. Springer, Berlin Heidelberg New York  
* Borradaile G (2003) Statistics of Earth Science Data – T eir Distribution in Time, Space and Orientation. Springer, Berlin Heidelberg New York  
* Carr JR (1994) Numerical Analysis for the Geological Sciences. Prentice Hall, Englewood Clif s, New Jersey  
* Davis JC (2002) Statistics and Data Analysis in Geology, T ird Edition. John Wiley and Sons, New York  
* Gonzalez RC, Woods RE, Eddins SL (2009) Digital Image Processing Using MATLAB – 2nd Edition. Gatesmark Publishing, LLC  
* Haneberg WC (2004) Computational Geosciences with Mathematica. Springer, Berlin Heidelberg New York  
* Harker A (1909) T e Natural History of Igneous Rocks, Macmillan, New York  
* Holzbecher E (2012) Environmental Modeling using MATLAB –  2nd Edition. Springer, Berlin Heidelberg New York  
* Menke W, Menke J (2012) Environmental Data Analysis with MATLAB. Springer, Berlin Heidelberg New York  
* Middleton GV (1999) Data Analysis in the Earth Sciences Using MATLAB. Prentice Hall, New Jersey  
* Press WH, Teukolsky SA, Vetterling WT, Flannery BP (2007) Numerical Recipes: The Art of Scientifc Computing – 3rd Edition. Cambridge University Press, Cambridge  
* Quarteroni A, Saleri F, Gervasio P (2014) Scientifc Computing with MATLAB and Octave – 4th Edition. Springer, Berlin Heidelberg New York  
* Richter CF (1958) Elementary Seismology. WH Freeman and Company, San Francisco  
* Swan ARH, Sandilands M (1995) Introduction to Geological Data Analysis. Blackwell Sciences, Oxford  
* Wilks DS (2011) Statistical methods in the atmospheric sciences – 3rd Edition. Academic Press, Elsevier, Amsterdam  